services:
  # Backend Service
  - type: web
    name: rag-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    
  # Frontend Service  
  - type: web
    name: rag-frontend
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: API_URL
        fromService:
          type: web
          name: rag-backend
          envVarKey: RENDER_EXTERNAL_URL
